### ISSUE TITLE
Rename Wapuu to Agent W. and don't show nick in chats

### ISSUE THREAD

**Issue by jasmussen** [tinkertinker/wp-calypso#10]
Currently the chatbot looks like this:

![screen shot 2016-05-20 at 10 34 06](https://cloud.githubusercontent.com/assets/1204802/15422010/722cc4c0-1e76-11e6-863b-40313db2584e.png)

We should update Wapuu's nickname (`meta.nick`, don't know where that's stored) so it shows up right as the img alt text. We should also not show it in the chat itself. My assumption is right now that it's unnecessary info, if we find out otherwise during the test we can add it back.

CC: @beaucollins

**Comment by beaucollins** [comment]
The nick and user information was being supplied by the tinkerchat server. I updated it to use Agent W.

**Comment by jasmussen** [comment]
I believe this was fixed a while back.
