### ISSUE TITLE
Scroll location jump on resize from sidebar to chat panel

### ISSUE THREAD

**Issue by mahangu** [tinkertinker/wp-calypso#13]
When you shrink the browser window so that the chat sidebar changes into a chat panel, the scroll bar of the chat panel <em>jumps</em> upwards, meaning that the user has to scroll down again to get to the last typed text.

Screen capture - 
https://cloudup.com/cE9GrWjkJZD

**Steps to reproduce**
1) Open a browser window, load the user facing site, and make sure the window is large enough for the chat sidebar to appear
2) Start a chat as a user
3) Resize the browser window so the chat sidebar changes into the chat panel

**Comment by andreabadgley** [comment]
cc: @jasmussen

**Comment by jasmussen** [comment]
Fixed in a recent commit, [](https://github.com/tinkertinker/wp-calypso/pull/3/commits/ef6b11f3ce133765a7920bbb90c4c2d8078b2895)! Great report, thanks.
