### ISSUE TITLE
Track User Location/Navigation

### ISSUE THREAD

**Issue by mjangda** [tinkertinker/wp-calypso#14]
As the user navigates around Calypso, we need to track their current page and report that to the service as an event (`navigation`?)

We need to limit the event such that it's not visible to the user (only operators [and bots?]).

Needed for https://github.com/Automattic/tinkerchat-hud/issues/49

**Comment by kriskarkoski** [comment]
Closing in favor of https://github.com/Automattic/happychat-hud/issues/49, we can add a corresponding issue in wp-calypso when it's being worked on
