### ISSUE TITLE
Track user's browser and system info

### ISSUE THREAD

**Issue by mjangda** [tinkertinker/wp-calypso#15]
As an added bit of info for HEs, when a user initiates a chat, we should grab a batch of data about the user's browser and system and send that to the service so it's available in the HUD.

**Comment by andreabadgley** [comment]
Thank you for thinking of this. Knowing the user's browser and OS is super helpful when troubleshooting.

**Comment by kriskarkoski** [comment]
Tracking this here: https://github.com/Automattic/happychat-hud/issues/458
