### ISSUE TITLE
Ongoing chat does not sync across browser sessions

### ISSUE THREAD

**Issue by mahangu** [tinkertinker/wp-calypso#16]
If a user is in an ongoing chat with us, and logs in from another browser/session, new chat messages that come in after they login, appear in the new browser/session. 

However, chat messages that have already been sent do not get synced across to the new browser session automatically. Ideally, the user should see the existing chat messages when they login from a new browser/session.

![screen shot 2016-05-30 at 11 45 58 am](https://cloud.githubusercontent.com/assets/10125810/15641144/5cab6302-265c-11e6-86a9-a2f262e499e8.png) ![screen shot 2016-05-30 at 11 46 08 am](https://cloud.githubusercontent.com/assets/10125810/15641146/5dc449f2-265c-11e6-8b72-9785f49683bb.png)

**Steps to reproduce**
1) As a user, start a chat from one browser/session
2) Login as the same user from another browser/session, and open chat
3) New messages will across both browsers/sessions, but existing messages will not

**Comment by andreabadgley** [comment]
Reproduced today in OSX El Capitan.

Current (existing) messages will not sync into a new session in a second browser. However, once the new session is opened, all subsequent messages will sync across browsers.
1. Log into https://lit-cove-83883.herokuapp.com/ in Chrome incognito window.
2. Type some messages & receive some messages from operator.
3. Log in as same user https://lit-cove-83883.herokuapp.com/ in Firefox private window.
4. Firefox chat is empty -- it does not show the chat messages from the Chrome session.
5. Type a message in Firefox chat.
6. Firefox chat message syncs to existing Chrome session.
7. Send a message from Chrome session.
8. Chrome message syncs to Firefox session.
9. HUD messages also sync to both sessions.

**Comment by andrewspittle** [comment]
A very similar thing happens upon a full page refresh. After a quick chat in Slack I'm commenting here as it's perhaps related.

Here's what happens:
1. I can start a new chat from My Sites.
2. I can click around in Calypso and the chat history persists (e.g. clicking to Reader).
3. If I do a page refresh (e.g. Command + R) the chat sidebar and its history disappears.
4. I can re-open a support chat but it's empty and back to the original welcome message.

I tested this in Safari 9.1.2 on OS X 10.11.6.

**Comment by kriskarkoski** [comment]
Related to https://github.com/Automattic/happychat/issues/8 as well

**Comment by andreabadgley** [comment]
Closing in favor of #35. Both should be fixed by fixing https://github.com/Automattic/happychat/issues/8.
