### ISSUE TITLE
Live chat scrolling on MBP in Safari: no overscroll bounce in chat window

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#18]
Tested on MacBook Pro in Safari using trackpad. A couple of minor issues:
1. When Safari is not focused, main body scrolls when hovering over chat, as reported in https://github.com/tinkertinker/wp-calypso/issues/12 (The reverse is not true: when Safari is not focused, only the main body scrolls when hovering over the main body -- chat does not scroll when hovering over main body).
2. When Safari is focused, scrolling works as expected when hovering over chat, in that scrolling doesn't bleed into main body at end of chat scroll. However, there is sometimes a small bounce in the main body on the 3rd - 10th swipe. 

Here's a 1:08 video showing the issues above when chatting as user in Safari at https://lit-cove-83883.herokuapp.com/:

https://cloudup.com/cze2D3R2lPq

cc @jasmussen

**Comment by jasmussen** [comment]
Thanks for the video, and thanks for this extensive testing. 

The bounce that happens here is, I think, called "overscroll bounce", and is something that started on iOS and then migrated to desktop Safari, then Chrome. 

The technique we've adopted for preventing scroll-bleed doesn't easily support this overscroll bounce. We can theoretically emulate it, but it'll never be perfect. 

Solutions to this include moving to one of these other methods for preventing scrollbleed:
- http://codepen.io/joen/pen/wGONLB
- http://codepen.io/joen/pen/Kzjgqy
- http://codepen.io/joen/pen/wGbBoe

Each of those come with their own sets of downsides, and they're all harder to implement than the one we've gone with. But I think it's worth leaving this ticket open for discussion, to see whether there's enough desire for the bounce that it's worth putting in the effort. I've taken the liberty of renaming the ticket to better help people looking for this. 

The focus/unfocus is indeed the same as #12.

**Comment by andreabadgley** [comment]
The bounce (or lack of bounce) doesn't bother me. I reported in case there were larger issues at play. I personally don't think it's worth putting a lot of effort into adding a bounce to the chat window.

**Comment by andreabadgley** [comment]
closing -- this is low priority
