### ISSUE TITLE
Live chat panel obscured on Calypso menus screen

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#20]
When window is sized such that live chat is the small panel instead of the full sidebar, the panel is obscured by the custom menu when on the Calypso menus screen at `/menus`: https://lit-cove-83883.herokuapp.com/menus/{siteURL}:

![chat_obscured_by_menu](https://cloud.githubusercontent.com/assets/9036382/15708984/2cfb2cee-27d0-11e6-8648-ababaf3a93d0.jpg)

It is not possible to click the chat to bring it forward. Tested in Chrome and Firefox with same results. Steps to repro:
1. Go to https://lit-cove-83883.herokuapp.com
2. Log in with WPcom credentials.
3. Resize window so that chat becomes small panel instead of sidebar.
4. Navigate to My Sites > Menus
5. Find a menu with several items on it (or create one), such that the menu extends low enough that it overlaps with the chat panel.
6. Menu obscures chat panel and it is not possible to see or access the chat.

When the window is expanded so that chat becomes a sidebar instead of a panel, everything works fine.

**Comment by andreabadgley** [comment]
cc: @jasmussen 

Here's a 15 sec video that demonstrates it a little more clearly:

https://cloudup.com/cbuPC5PBLvN

**Comment by jasmussen** [comment]
You're pretty good at this! Should be fixed by https://github.com/tinkertinker/wp-calypso/pull/3/commits/709183bbc3ca334944d610839bb52156b134fbdc
