### ISSUE TITLE
Stats screen text fields bleed through live chat panel

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#21]
When scrolling through Insights and other stats screens in Calypso, a small amount of white at the edge of the text field bleeds through to the chat panel:

<img width="449" alt="stats bleed 1" src="https://cloud.githubusercontent.com/assets/9036382/15709251/b9324f48-27d1-11e6-89a2-e19d2cc23565.png">

Steps to reproduce:
1. Go to https://lit-cove-83883.herokuapp.com
2. Log in with WPcom credentials.
3. Resize window so that chat becomes small panel instead of sidebar.
4. Navigate to My Sites > Stats
5. Scroll through the different stats screens.
6. See white edges of fields, eg. in the Comments section of the Insights screen, or the Followers section (sections must contain content for this to occur).

Occurs in both Firefox and Chrome on MBP.

cc @jasmussen

**Comment by jasmussen** [comment]
Should be fixed by https://github.com/tinkertinker/wp-calypso/pull/3/commits/709183bbc3ca334944d610839bb52156b134fbdc
