### ISSUE TITLE
Scroll broken in input field when scroll exists in sidebar/panel

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#23]
Steps to reproduce
1. Starting at URL: https://lit-cove-83883.herokuapp.com/
2. Open chat using Support Chat link in left footer
3. Send enough messages to require scrolling in the chat sidebar/panel
4. Type a long message in the input field. When the long message is long enough to require scrolling in the input field, attempt to scroll the input field before sending the message.
5. Hover over or click into input field and attempt to scroll.
6. Chat sidebar or panel scrolls, but input field does not.

I expected the input field to scroll when it is active or when I hovered over it. Instead, the chat sidebar or panel scrolls. Tested in Firefox, Chrome, and Safari in OSX El Capitan and it occurs in all three browsers

![hud-scroll](https://cloud.githubusercontent.com/assets/9036382/16080091/16d9eb84-32d5-11e6-929f-d3ab45c8d28a.gif)

Thank you @dllh for reporting and for the gif.

**Comment by beaucollins** [comment]
You should be able to scroll the input field now on desktop browsers.

**Comment by andreabadgley** [comment]
Tested and I am able to scroll input field in sidebar and in panel (Chrome and Firefox, OSX El Capitan).
