### ISSUE TITLE
Support Chat footer link does not work in Safari

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#24]
Steps to repro:
1. Open Safari in OSX El Capitan
2. Start at URL: https://lit-cove-83883.herokuapp.com/
3. Click Support Chat link in left footer
4. Nothing happens -- support chat does not open as expected.

**Comment by beaucollins** [comment]
It looks like the floating panel is no longer working. If you widen your screen (if possible) does the sidebar show up?

I'll take a look at what's causing this.

**Comment by andreabadgley** [comment]
Yep, you're right. When I widen my screen, the sidebar shows up. Only the panel is missing.

**Comment by beaucollins** [comment]
This should be fixed now via 3c588ec48a1abffa4e26f89f5e12248827edfc92

**Comment by andreabadgley** [comment]
Yep, works now. Thanks Beau!
