### ISSUE TITLE
Chat sidebar obscures Calypso screens

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#26]
#### Steps to reproduce
1. Starting at URL: https://lit-cove-83883.herokuapp.com
2. Resize screen so that chat expands to right sidebar.
3. On Reader, chat sidebar obscures right side of posts.
4. Click to My Sites > Stats.
5. Chat sidebar covers right hand side of stats.
6. Click around other Calypso screens; chat sidebar covers the right side.

It looks like the Calypso screen is not centering between the left and right sidebars but is instead keeping its original centering, and the chat sidebar covers it on the right side.
#### Browser / OS version

OS X El Capitan, Chrome, Firefox
#### Screenshot / Video

https://cloudup.com/c4Cw_z9nSGY

**Comment by beaucollins** [comment]
This is fixed and deployed.
