### ISSUE TITLE
Improve chat styling on narrow screens

### ISSUE THREAD

**Issue by kriskarkoski** [tinkertinker/wp-calypso#28]
On narrower screens the Happychat window is not docked in full-height on the right side, but instead floats in the bottom-right corner and covers over half of the width, which feels out of place since it covers elements of Calypso. I think we should either make it narrower to be more into the right-corner like our previous chat implementation or take up the full-width on the bottom of the screen.

![screen shot 2016-07-27 at 11 21 31 am](https://cloud.githubusercontent.com/assets/1900444/17223081/0bc086c0-54c9-11e6-80ce-4504309da96a.png)

**Comment by andreabadgley** [comment]
This is the intended look that was previously in use:
![chat panel](https://cloud.githubusercontent.com/assets/9036382/17225553/75c42b12-54d3-11e6-844c-1a9ec34d1e89.jpg)

**Comment by andreabadgley** [comment]
cc: @jasmussen This happens in both Chrome and Firefox

**Comment by andreabadgley** [comment]
Closing in favor of #52 .
