### ISSUE TITLE
Flip the chat bubble for users

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#30]
Originally reported in https://github.com/Automattic/happychat-hud/issues/318 by @eduardozulian:

At the moment, we are using the same chat bubble for both user and operator:

![captura de tela 2016-08-15 as 10 51 12](https://cloud.githubusercontent.com/assets/1136160/17666599/472cd7ce-62d7-11e6-8016-a17ba9e91d15.png)

The idea here is just flip the tail and other elements to point the chat bubble directly at the user:

![captura de tela 2016-08-15 as 11 29 58](https://cloud.githubusercontent.com/assets/1136160/17667539/ad4543a8-62db-11e6-914b-9579901758ef.png)

**Comment by beaucollins** [comment]
A css class change actually caused this regression. The customer's bubble was white and pointed to the right. Fixed and being deployed.

![screen shot 2016-08-26 at 3 57 42 pm](https://cloud.githubusercontent.com/assets/19795/18022701/e0eeb48c-6ba5-11e6-9cb0-1ab109303807.png)
