### ISSUE TITLE
Add contrast for links in live chat component

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#31]
Links in the user client are a bit hard to read. Can we increase the contrast? In the HUD, the hex color for links is #9FE9FC.

Here's what they look like in the user client:
<img width="364" alt="poor contrast for links in user client" src="https://cloud.githubusercontent.com/assets/9036382/18063362/a769f622-6df8-11e6-84c2-6cdfd03f78e9.png">

Here's what they look like in the HUD:
<img width="575" alt="hud links" src="https://cloud.githubusercontent.com/assets/9036382/18063426/e5b9a486-6df8-11e6-89e5-bd8c54502684.png">

**Comment by rachelmcr** [comment]
+1 to this. The contrast on the links is fine if I send the link as a user (on white background) but it's very hard to read links sent by the operator.

**Comment by andreabadgley** [comment]
cc: @jasmussen

**Comment by jasmussen** [comment]
This is fixed when https://github.com/Automattic/wp-calypso/pull/8279 is merged in. Closing here.
