### ISSUE TITLE
User isn't notified when the operator has ended chat

### ISSUE THREAD

**Issue by ashercantrell** [tinkertinker/wp-calypso#33]
This may be a wontfix, but currently with Olark, users see a short notification that the operator has ended the chat. It appears that Happychat doesn't have this at the moment from my testing.

**Comment by andreabadgley** [comment]
Related: https://github.com/Automattic/happychat/issues/21, https://github.com/Automattic/happychat/issues/22, https://github.com/Automattic/happychat/issues/18

**Comment by andreabadgley** [comment]
Reported at the service level here: https://github.com/Automattic/happychat/issues/102.
