### ISSUE TITLE
Lost chat while navigating in the same tab

### ISSUE THREAD

**Issue by rachelmcr** [tinkertinker/wp-calypso#35]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Click "Support Chat" to start a new chat
3. Enter a message and go back and forth with the operator
4. Click "My Sites" in the same browser tab
#### What I expected

I expected the chat to follow me to the new page.
#### What happened instead

I lost the chat. The chat sidebar (on the right) closed, and when I clicked "Support Chat" again it opened a new chat window to start a new chat. I never got the previous chat back.

However, my operator (Andrea) still had my chat and I could continue chatting with her.

I then tried visiting other Calypso pages, and I couldn't reproduce the issue even when I switched from the Reader to the My Sites page again later. The chat followed me between pages as expected after that.
#### Browser / OS version

Chrome 52.0.2743.116 / Mac OS X 10.11.6
#### Context / Source
# manual-testing

**Comment by rachelmcr** [comment]
I can consistently reproduce this issue with a different set of steps:
1. Starting at URL: https://wordpress.com/me/chat
2. Enter a message to start a new chat (no reply from operator yet)
3. Click "Reader" in the masterbar to open https://wordpress.com/
4. The chat window is gone, so click "Support Chat" in the bottom left to reopen the chat window. The initial message in my chat is still there.
5. Click the Gravatar in the masterbar to open https://wordpress.com/me (the chat window is still open on the right)
6. Click "Support Chat" in the sidebar to go back to https://wordpress.com/me/chat
7. The page fully reloads, and a new chat begins (my initial message is gone, and I see the message inviting me to start a new chat)

**Comment by andreabadgley** [comment]
Closing in favor of #29 .
