### ISSUE TITLE
Collapse open chat when navigating from other screen to /me/chat

### ISSUE THREAD

**Issue by rachelmcr** [tinkertinker/wp-calypso#36]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/
2. Click "Support Chat" to start a new chat
3. Enter a message and go back and forth with the operator
4. Click on your Gravatar in the masterbar to go to the `/me` page
5. Click "Support Chat" in the left sidebar to go to https://wordpress.com/me/chat
#### What I expected

I expected to see a full-screen chat.
#### What happened instead

I saw the full-screen chat with the chat sidebar overlapping it on the right.
#### Browser / OS version

Chrome 52.0.2743.116 / Mac OS X 10.11.6
#### Screenshot / Video

![screen shot 2016-08-31 at 12 28 05 pm](https://cloud.githubusercontent.com/assets/8658164/18128354/30c448fc-6f7d-11e6-910e-0b4cb4016ac6.png)
#### Context / Source
# manual-testing

**Comment by andreabadgley** [comment]
Tested today and this is fixed.
