### ISSUE TITLE
Change opening "A chat history will be stored here" message to user

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#38]
When a user opens a new chat in Happychat, they receive this message:

> This is the beginning of your chat history with WordPress.com support. A chat history will be stored here.

Until https://github.com/Automattic/happychat/issues/8 is implemented, we should change this message to:

> Welcome to WordPress.com support chat!

or something similar :-)

**Comment by andreabadgley** [comment]
@kriskarkoski mentioned that the user never gets an introduction to Agent W. Perhaps this is a good place to intro?

**Comment by kriskarkoski** [comment]
Here's an example from @mjangda in Slack that we might be able to use for inspiration:

![image](https://cloud.githubusercontent.com/assets/1900444/18848838/3ca09cc6-83fe-11e6-9513-055cd64af34b.png)

**Comment by jasmussen** [comment]
Let's keep it simple for now. Will be fixed when https://github.com/Automattic/wp-calypso/pull/8315 is merged.
