### ISSUE TITLE
Chat window breaks when browser is resized to less than 1040px wide

### ISSUE THREAD

**Issue by rachelmcr** [tinkertinker/wp-calypso#39]
#### Steps to reproduce
1. Starting at URL: Any Calypso URL, e.g. https://wordpress.com/
2. Make sure your browser window is wider than 1040 px and start a new chat
3. Resize the window so it is 1040 px wide or smaller
#### What I expected

I expected the chat window to respond to the smaller browser width/size.
#### What happened instead

The window "detached" from the sidebar (not connected to the right or top edges of the window) and just floated there, covering the content and not changing width until the window became smaller than the chat window's width.
#### Browser / OS version

Chrome 52.0.2743.116 / Mac OS X 10.11.6
#### Screenshot / Video

![screen shot 2016-08-31 at 6 04 48 pm](https://cloud.githubusercontent.com/assets/8658164/18139066/a5892e08-6fa7-11e6-9695-b8fb2071e1e8.png)
#### Context / Source
# manual-testing

**Comment by andreabadgley** [comment]
cc: @jasmussen

**Comment by kriskarkoski** [comment]
Looks like this might be related to https://github.com/tinkertinker/wp-calypso/issues/52

**Comment by jasmussen** [comment]
This should be fixed when https://github.com/Automattic/wp-calypso/pull/8317 gets merged in.
