### ISSUE TITLE
Add "Support Chat" link to Me menu on front of site

### ISSUE THREAD

**Issue by rachelmcr** [tinkertinker/wp-calypso#42]
#### Steps to reproduce
1. Starting at the front page of your site
2. Click the Gravatar in the admin bar to open the /me menu
3. Look for "Support Chat" link (nothing appears under the Help link)
4. Click on "My Profile" to open https://wordpress.com/me
5. Look for "Support Chat" link (appears under the Help link in the sidebar)
#### What I expected

I expected the links in the /me menu on the front of the site (under the user's Gravatar in the admin bar) to match the links in the sidebar at https://wordpress.com/me
#### What happened instead

There is no Support Chat link in the /me menu on the front of the site.
#### Browser / OS version

Chrome 52.0.2743.116 / Mac OS X 10.11.6
#### Screenshot / Video

Front of site:

![screen shot 2016-09-01 at 6 40 08 pm](https://cloud.githubusercontent.com/assets/8658164/18177974/656b1516-7074-11e6-92cd-00341f90fe4b.png)

Sidebar at https://wordpress.com/me:

![screen shot 2016-09-01 at 6 40 43 pm](https://cloud.githubusercontent.com/assets/8658164/18177986/6e071422-7074-11e6-8826-73477598ee30.png)
#### Context / Source
# manual-testing

**Comment by rickybanister** [comment]
I came here to report the same thing. I think we should build a 'help menu' component for the sidebar so that these links are displayed consistently across all sidebars as a footer.

**Comment by andreabadgley** [comment]
Saving this for the future as we might remove the Support Chat option in the first go round. In Happychat's first iteration, users will go through the current flow of **Help → Contact** to open chat. The Support Chat link would only then appear for users who have an active chat going. Context [here](https://happychatp2.wordpress.com/2016/09/19/how-should-users-access-happychat/#comment-13).

**Comment by kriskarkoski** [comment]
Closing since Help is linked and that is our only path into Happychat at the moment
