### ISSUE TITLE
Chat does not work well from theme info page (easy to lose the chat)

### ISSUE THREAD

**Issue by rachelmcr** [tinkertinker/wp-calypso#43]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design
2. Select a site and click the Support Chat link to start chatting
3. Click on a theme to view the theme info page (problem 1)
4. Click the "X" on the chat to close it (problem 2)
5. Go back to the All Themes page and click Support Chat to find the chat again
6. Click on a theme to view the theme info page again
7. Click the Setup or Support tabs on the theme info page
8. Click a link on either the Setup or Support tabs (problem 3)
#### What I expected

Problem 1:
I expected the chat window to appear to the right of the theme info.

Problem 2:
I expected to be able to reopen the chat window after I closed it.

Problem 3:
I expected the links on the theme info page to open in a new window, or to bring my chat with me when I clicked on them.
#### What happened instead

Problem 1:
The chat window overlaps the theme info.

Problem 2:
The chat window disappears, and there is no Support Chat link to reopen it. (You have to go back to the All Themes page and click Support Chat to reopen it.)

Problem 3:
The links in the theme info page open in the same tab, and they aren't in Calypso, so I lose my chat entirely.

When I go back (with the browser back button), the theme info page doesn't show the chat window anymore. When I go back again (with either the browser back button or the "<- All Themes" link on the page) the chat window isn't there. When I click Support Chat to open the chat again, it start a new chat, losing my previous chat.
#### Browser / OS version

Chrome 52.0.2743.116 / Mac OS X 10.11.6
#### Screenshot / Video

Problem 1:
![screen shot 2016-09-01 at 7 16 17 pm](https://cloud.githubusercontent.com/assets/8658164/18179108/ebf34cf8-7078-11e6-9de0-81ce7694a7de.png)

Links that cause problem 3 (screenshot taken after I lost my previous chat and was prompted to start a new one):
![screen shot 2016-09-01 at 7 20 07 pm](https://cloud.githubusercontent.com/assets/8658164/18179216/4d9a1626-7079-11e6-9a2b-d2724f2fb16d.png)
#### Context / Source
# manual-testing

**Comment by andreabadgley** [comment]
cc: @jasmussen

**Comment by andreabadgley** [comment]
May be same underlying cause as #51. Check both tickets when fix is implemented.

**Comment by jasmussen** [comment]
The broken layout will be fixed when https://github.com/Automattic/wp-calypso/pull/8320 gets merged in. 

Problems 2 and 3 are hard to solve, so I'll open a separate ticket.
