### ISSUE TITLE
Posting activity graph is cut off after starting a new chat

### ISSUE THREAD

**Issue by andrewspittle** [tinkertinker/wp-calypso#44]
If you initiate a new chat from `stats/insights/siteurl` the posting activity graph is cut off by the chat sidebar.

**Steps to reproduce**
1. Open the Insights page for a site. e.g. https://wordpress.com/stats/insights/andrewspittle.com
2. Click "Support Chat" to start a new chat.
3. Note the display of the "Posting Activity" section of the page.
4. The most recent month or so will be cut off.

You can see this in the blow screenshots. First, this is what the posting activity graph looks like when first opening the page:

<img width="748" alt="screen shot 2016-09-02 at 11 07 56 am" src="https://cloud.githubusercontent.com/assets/86101/18213650/23140b52-70fe-11e6-9fb9-4250ecea95b8.png">

This, then, is what it looks like after you start a chat.

<img width="938" alt="screen shot 2016-09-02 at 11 08 05 am" src="https://cloud.githubusercontent.com/assets/86101/18213659/2d29b114-70fe-11e6-96ce-fef6a8ec3af3.png">

Note how half of August and all of September is cut off. Ideally initiating a chat should not cause part of the page to be cut off.

I tested this in Safari 9.1.2 on OS X.

**Comment by andreabadgley** [comment]
cc @jasmussen

**Comment by jasmussen** [comment]
Fixed when https://github.com/Automattic/wp-calypso/pull/8312 is merged.
