### ISSUE TITLE
Scrolling Issue: no notification to user that they operator has responded/they should scroll down.

### ISSUE THREAD

**Issue by professarah** [tinkertinker/wp-calypso#45]
#### Steps to reproduce

**No Notification When User Scrolls Up in Conversation:**
1. Starting as user, log into chat.
2. Begin conversation with operator. Operator responds.
3. Create enough of a conversation for a reasonable backscroll. (Note that the scroll does not follow the conversation--it stays at the top.)
4. Operator responds as user is reading the backscroll above.
5. There is no notification/indication that the operator has responded.

**No Notification to user that operator has responded in first chatbox window (when opening multiples)**
1. Starting as user, log into chat.
2. Begin conversation with operator. Operator responds.
3. Click operator link to open second calypso browser and/or open another calypso page.
4. Open second chatbox for operator. Write message to operator in second window.
5. Operator responds--user will see the operator's response in the second chat window.
6. Go back to first chat window--it looks as though operator did not respond, however, if you scroll down, you can see the operator.
#### What I expected

If a user scrolled up in a chat to read something that was sent before, I expected to either have the chat jump back down to the operator response or have some sort of notification. 

Additionally, as the chats get longer and longer, the scroll does NOT follow the conversation; it sticks to the top.

Across multiple chats--operator's instructions to continue across multiple chat boxes.
#### What happened instead

When a user scrolls up towards the top, they don't get any kind of notification that an operator has replied to the user and that he or she should scroll down.

This is similar to https://github.com/tinkertinker/wp-calypso/issues/16 (ongoing chat does not sync across browser sessions)--along with the async across chats, if a user opens a second chatbox in a second chat window and the operator responds, the text from the operator will appear in the second window. It will ALSO appear in the first chatbox, but there's no indication that they should scroll down.
#### Browser / OS version

Chrome 52, OSX
#### Screenshot / Video

<b>Example of chat not scrolling with lengthier conversation:</b>
<img src="https://testingsierraecho.files.wordpress.com/2016/09/screen-shot-2016-09-02-at-12-37-52-pm.png"> 
I'd typed quite a bit and my operator had replied as well, but it did not scroll down.<br><br>
<br>
<b>Conversation continued across both chats, BUT there was no indication that the operator had responded when I switched back to the first chat (when I was looking at the second screen). A notification to scroll down would be very helpful!</b>

<b>Second Chat Window--I can see that the operator responded since I was looking at this window.</b>
<img src="https://testingsierraecho.files.wordpress.com/2016/09/screen-shot-2016-09-02-at-12-39-40-pm.png"><br><br>
<b>First Chat Window: Since this screen was not open in my browser, it looked like the operator did not respond in my first chat box (when I eventually switched back.)</b> Conclusion Operator's response DOES load into the first window, but only if I scroll down. There was no indication that I, the user, should scroll down to see it.
<img src="https://testingsierraecho.files.wordpress.com/2016/09/screen-shot-2016-09-02-at-12-39-48-pm.png">

**Comment by andreabadgley** [comment]
cc: @jasmussen

**Comment by jasmussen** [comment]
This is a great ticket, what an interesting issue. 

I fired up a hangouts conversation, asked for a message, scrolled way back, just to see how Hangouts handles it. Interestingly — virtually nothing happens. Not even a sound. Just a brief flash of the scrollbar to indicate that the chat grew longer. This suggests to me there's no universal "comme il faut" for solving this problem.

Two ideas: 
1. a notification sound. Every chat made by an HE makes a little pop sound, just like it does in the HUD. 
2. a little notification bubble that shows up at the bottom indicating the presence of new replies

Mockup:

![screen shot 2016-09-28 at 12 58 24](https://cloud.githubusercontent.com/assets/1204802/18911095/4f031d52-857b-11e6-8fb5-d5264cd55401.png)

Technically this is beyond me to build I think. Any takers, @batmoo, @georgeh ?

**Comment by kriskarkoski** [comment]
This will be fixed via https://github.com/Automattic/happychat-hud/issues/453, https://github.com/tinkertinker/wp-calypso/issues/55 (in review), and https://github.com/Automattic/wp-calypso/pull/10903 (in development)
