### ISSUE TITLE
Typing lags in Safari in live chat component

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#47]
_Originally reported by @kriskarkosi in https://github.com/Automattic/happychat/issues/98:_

> Chatting as a user, typing lags in Safari (seen in 9.1.3) even on a brand new chat. Reported by @shaunandrews during our a8c testing. Video of the issue below:
> 
> ![lag](https://cloud.githubusercontent.com/assets/1900444/18225375/c24532ee-71be-11e6-9c76-3d8149020635.gif)
> 
> Similar sounding issue in https://github.com/Automattic/happychat-hud/issues/358, but the cause there seems to be a long chat history, which was not the case here.

I tried to replicate this in Safari on 9.1.3 in OS X El Capitan 10.11.6 today but was unable.

**Comment by kriskarkoski** [comment]
This appears to have been fixed along the way as it has not come up in 2+ weeks since launching
