### ISSUE TITLE
Smarter link behavior: Calypso in same tab, everything else in new tab

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#48]
_Originally reported by @kriskarkoski in https://github.com/Automattic/happychat/issues/99_

> We recently changed all links to open in a new tab to avoid users losing chat unexpectedly when we send them anywhere other than Calypso, but in testing this means that Calypso links open in a new tab with chat closed and clicking the Support Chat link again loses the chat history.
> 
> We should improve this before launching to users to open all Calypso links in the same tab so chat can follow the user, while WP Admin, en.support, and any other non-Calypso links open in a new tab so chat remains open in the original tab.

Related: https://github.com/tinkertinker/wp-calypso/issues/6#issuecomment-243218894

**Comment by mjangda** [comment]
This is live and mostly working.

There are two bugs that I'm fixing:
- A URL without a scheme is not hyperlinked (this bug was fixed in HUD)
- A internal URL with a scheme that doesn't match (e.g. I send `http://wp.com/me` and the user is on `https`) results in a reload.

**Comment by mjangda** [comment]
The 2nd issue in the comment above was fixed in https://github.com/Automattic/wp-calypso/pull/8831

The 1st issue needs to be fixed in the service (not extracting schema-less urls)

**Comment by mjangda** [comment]
Much better now. There are some things that don't match like just `example.com` but that's something we can look at in the future.
