### ISSUE TITLE
Edit Post URL Link Icon Hidden in Editors with Happychat open

### ISSUE THREAD

**Issue by kriskarkoski** [tinkertinker/wp-calypso#51]
Opening Happychat while in the Post editor (wordpress.com/posts) forces the "Edit Post URL" link icon off screen:

<img width="1280" alt="screen shot 2016-09-27 at 12 35 02 pm" src="https://cloud.githubusercontent.com/assets/1900444/18882841/e8e7b252-84ae-11e6-8326-10b3aedd9566.png">

Here's what it looks like without Happychat open:

<img width="1280" alt="screen shot 2016-09-27 at 12 31 43 pm" src="https://cloud.githubusercontent.com/assets/1900444/18882858/f329bdc8-84ae-11e6-94f2-bbaba4067d25.png">

Instead, we should indent the icon and title with Happychat open so it remains accessible like it does in a narrower browser window:

<img width="997" alt="screen shot 2016-09-27 at 12 33 46 pm" src="https://cloud.githubusercontent.com/assets/1900444/18882879/096817c4-84af-11e6-9545-26fa7180ed38.png">

The issue is also present in the Page editor, but looks slightly different since the permalink is always visible there. Instead, the link icon is mostly cut off:

<img width="1280" alt="screen shot 2016-09-27 at 12 35 02 pm" src="https://cloud.githubusercontent.com/assets/1900444/18882902/28e8148c-84af-11e6-85ff-bd60709ff639.png">

It should look more like this with the icon remaining visible in narrower windows (though there looks to be some existing padding issues):

<img width="976" alt="screen shot 2016-09-27 at 12 38 33 pm" src="https://cloud.githubusercontent.com/assets/1900444/18882964/61e80b7a-84af-11e6-995c-73e66b3c316e.png">

All of these were seen on OS X 10.11.6 in Chrome 53

**Comment by andreabadgley** [comment]
May be same underlying cause as #43. Check both tickets when fix is implemented.

**Comment by jasmussen** [comment]
Should be fixed when https://github.com/Automattic/wp-calypso/pull/8319 gets merged in. Won't fix #43.
