### ISSUE TITLE
Chat box is extra wide in some cases

### ISSUE THREAD

**Issue by kriskarkoski** [tinkertinker/wp-calypso#52]
In a browser window that is narrow enough for Happychat to no longer takes up the full right side it is occasionally displaying in an extra wide version rather than the smaller version docked in the bottom right corner. 

Here is how it should look:

<img width="1005" alt="screen shot 2016-09-27 at 1 03 11 pm" src="https://cloud.githubusercontent.com/assets/1900444/18884509/aee56782-84b5-11e6-93b0-2d61f72e2cf9.png">

And here is how it's occasionally displaying:

<img width="919" alt="screen shot 2016-09-27 at 1 08 00 pm" src="https://cloud.githubusercontent.com/assets/1900444/18884517/bb0da394-84b5-11e6-81b0-46c2dc631709.png">

Both of these were seen in Chrome 53 on OS X 10.11.6. 

@andreabadgley added:

> I got the wide chat as a user, then typed something and it got small
> Then Agent W replied with no opers available and it got wide again

**Comment by andreabadgley** [comment]
cc @jasmussen

**Comment by jasmussen** [comment]
The wide chatbox is covered in a different ticket, but the overlapping gradient should be fixed when https://github.com/Automattic/wp-calypso/pull/8317 gets merged in. Actually the wide box will too.
