### ISSUE TITLE
Open Customize in new tab if user has active chat session

### ISSUE THREAD

**Issue by kriskarkoski** [tinkertinker/wp-calypso#53]
The "Customize" option next to Themes in the Calypso sidebar appears to be the only option linking to a non-Calypso page, which means if the user selects it while chatting with us they will no longer be able to see their chat until they navigate back to Calypso, and then it may be collapsed and hard to find. If feasible, we should force Customize to open in a new tab if the user has an active chat session with us.

![customize highlight](https://cloud.githubusercontent.com/assets/1900444/18884724/9e2bba08-84b6-11e6-9eea-7ff82409980b.jpg)

**Comment by jasmussen** [comment]
This is fixed when https://github.com/Automattic/wp-calypso/pull/8925 gets merged!

**Comment by jasmussen** [comment]
Merged!
