### ISSUE TITLE
Provide sound notifications to user in live chat component

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#55]
When user's chat tab is not focused, provide a browser sound notification when agent has left a new message.

_Separated out from #7 for easier tracking_

**Comment by kriskarkoski** [comment]
A user [mentioned](https://a8c.slack.com/archives/livechat/p1484565487039170) missing this after our switch to Happychat and I've noticed a higher frequency of users not responding right away compared to Olark I think mostly because of the lack of notification.

**Comment by andrewspittle** [comment]
I wonder if some of the customers we're missing have also minimized the chat sidebar into the little bubble icon. In those cases when there's a new message we leave the icon background Calypso blue. In addition to a sound we could flag that square icon area notification-orange to indicate there's new chat activity.

**Comment by kriskarkoski** [comment]
> we could flag that square icon area notification-orange to indicate there's new chat activity.

I think this would be a great idea and mentioned something similar [here](https://github.com/tinkertinker/wp-calypso/issues/54), but lost track of it when the main issue there got resolved.

@jasmussen Is the color change for the icon something you could look at?

**Comment by jasmussen** [comment]
> @jasmussen Is the color change for the icon something you could look a

I'm afraid the technical bits to make the dot light up requires the master skills of someone like @beaucollins, I know he's already busy though. However, part of the work should be done. Per https://github.com/Automattic/wp-calypso/pull/8578 there is a CSS class that can be applied to the HappyChat icon in the bottom left footer: `sidebar__footer__support-chat-unread`. This is already merged in, and should look like this:

![6faee818-8c99-11e6-94df-927afd7d6aaa](https://cloud.githubusercontent.com/assets/1204802/22029975/7dc5f958-dcdc-11e6-80b4-fb0c0b950e05.png)

What remains to be done is setting that CSS class when there's new stuff. Help me Beau-bi Wan Kenobi, you're my only hope!

**Comment by jordwest** [comment]
I have a PR ready for review that adds the notification sounds for users: https://github.com/Automattic/wp-calypso/pull/10724

**Comment by beaucollins** [comment]
Badge is being added in automattic/wp-calypso#10903

**Comment by kriskarkoski** [comment]
Closing since both pieces are in progress and we're clearing this repo out
