### ISSUE TITLE
Add notification dot to Support Chat link when there's a new msg from agent

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#57]
When a user has minimized the chat window, add a notification dot when there is an unread message from an agent.

![happychat notification](https://cloud.githubusercontent.com/assets/9036382/17225367/a1c839ca-54d2-11e6-8d3b-8bee3e47a747.png)

_Separated out from #7 for easier tracking_

**Comment by jasmussen** [comment]
This might have to change depending on what we decide in #34. Could be we have to make it a flashing panel instead.

**Comment by jasmussen** [comment]
Working on this issue in this branch: https://github.com/Automattic/wp-calypso/pull/8578

— could use some pro-level-JS help!

**Comment by kriskarkoski** [comment]
In progress in https://github.com/Automattic/wp-calypso/pull/10903
