### ISSUE TITLE
Opening external Calypso links in same window loses chat

### ISSUE THREAD

**Issue by jasmussen** [tinkertinker/wp-calypso#58]
Some links in Calypso open a non-react page, in the same window. If you were in a chat at the time, you obviously lose the chat. 

In #43, @rachelmcr notes that this is the case on theme pages. 

Should we add a "Are you sure you want to leave this page" JavaScript prompt, like the Happychat HUD has, to at least alert the user what's about to happen?

**Comment by kriskarkoski** [comment]
With the exception of a Plugins issue in https://github.com/Automattic/happychat/issues/167 non-Calypso links open in a new window so Happychat is not lost. This behavior will also be improved once https://github.com/Automattic/wp-calypso/issues/10793 is in place
