### ISSUE TITLE
Make URLS clickable in live-chat component

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#6]
When an operator provides a URL for a user to click in chat, the URL is not clickable. User must copy URL and paste into browser to open the link.

**Comment by andreabadgley** [comment]
cc @johngodley since you fixed a similar issue [here](https://github.com/Automattic/happychat-hud/issues/128).

**Comment by andreabadgley** [comment]
More notes on this:
- If link is in Calypso, like https://wordpress.com/me, user should be taken to new Calypso screen in the same tab.
- If link is not in Calypso, like http://en.support.wordpress.com/menus/, link should open in new tab.

**Comment by mjangda** [comment]
@beaucollins since you're looking into this, we have the auto-formatter lib in HUD that we probably can re-use here.

**Comment by beaucollins** [comment]
Ok. Another thing I'm looking at is having a middleware that can perhaps do some even fancier things by detecting if links are for wordpress.com blogs, internal calypso screens or external site links and adding information based on that.

**Comment by andreabadgley** [comment]
Woot! Links work for users now :-)

**Comment by beaucollins** [comment]
For future consideration: links within calypso should open within calypso. Right now it will launch a new browser window.
