### ISSUE TITLE
Feature: Smiley and emoji conversion

### ISSUE THREAD

**Issue by jasmussen** [tinkertinker/wp-calypso#61]
HEs often, depending on the conversation, add smileys or emoji.

Emoji work, and smileys show up as text smileys, so that's all good. But long term it would be nice if they both behaved like they do on WP.com, where `:)` is converted to 😀, and that smileys and emoji alike use the Twemoji set. 

Not a high priority.

**Comment by kriskarkoski** [comment]
Moved to https://github.com/Automattic/happychat/issues/191
