### ISSUE TITLE
Chat panel doesn't wrap long URLs

### ISSUE THREAD

**Issue by mahangu** [tinkertinker/wp-calypso#9]
Currently, when a longer URL is entered in the chat, the chat panel doesn't wrap it to the panel's exact dimensions, and instead clips the URL, and makes this extra content content accessible via both a horizontal and a vertical scrollbar.

![screen shot 2016-05-09 at 5 45 04 pm](https://cloud.githubusercontent.com/assets/10125810/15113338/46603542-1611-11e6-89c6-5b5952bec07e.png)

That chat panel should not display scrollbars here, and should instead wrap long URLs to the panel's exact dimensions.

**Comment by jasmussen** [comment]
Fixed in the most recent commit to the try/live-chat branch ^^

**Comment by andreabadgley** [comment]
Looks like things are now being pushed to the left. A link was wrapped in the chat bubble but pushed Agent W off:
<img width="286" alt="agent w cut off when long text" src="https://cloud.githubusercontent.com/assets/9036382/15441208/9c97d8c2-1ea7-11e6-8c78-d674d1d88c46.png">

And when I added unbroken text (not links) it pushed the chat bubble out to the left:
<img width="298" alt="pls wrap text" src="https://cloud.githubusercontent.com/assets/9036382/15441210/a182fdee-1ea7-11e6-8871-e025e4825511.png">

**Comment by jasmussen** [comment]
Fixed the wrapping in a recent commit.
